-- 修复AgentTrace的agentName null约束
ALTER TABLE "AgentTrace" ALTER COLUMN "agentName" DROP NOT NULL;
ALTER TABLE "AgentTrace" ALTER COLUMN "content" DROP NOT NULL;
ALTER TABLE "AgentTrace" ALTER COLUMN "simulationId" DROP NOT NULL;

-- 同时修复其他可能有NOT NULL约束的字段
ALTER TABLE "Simulation" ALTER COLUMN "type" DROP NOT NULL;
ALTER TABLE "Simulation" ALTER COLUMN "seedInput" DROP NOT NULL;
ALTER TABLE "Simulation" ALTER COLUMN "status" DROP NOT NULL;
ALTER TABLE "Simulation" ALTER COLUMN "userId" DROP NOT NULL;

ALTER TABLE "GraphNode" ALTER COLUMN "nodeType" DROP NOT NULL;
ALTER TABLE "GraphNode" ALTER COLUMN "name" DROP NOT NULL;

ALTER TABLE "GraphEdge" ALTER COLUMN "fromNodeId" DROP NOT NULL;
ALTER TABLE "GraphEdge" ALTER COLUMN "toNodeId" DROP NOT NULL;
ALTER TABLE "GraphEdge" ALTER COLUMN "relationType" DROP NOT NULL;

ALTER TABLE "ScenarioOutcome" ALTER COLUMN "label" DROP NOT NULL;
ALTER TABLE "ScenarioOutcome" ALTER COLUMN "simulationId" DROP NOT NULL;

ALTER TABLE "WhatIfBranch" ALTER COLUMN "simulationId" DROP NOT NULL;
ALTER TABLE "WhatIfBranch" ALTER COLUMN "hypotheticalChange" DROP NOT NULL;

ALTER TABLE "UserMemory" ALTER COLUMN "userId" DROP NOT NULL;
ALTER TABLE "UserMemory" ALTER COLUMN "type" DROP NOT NULL;
ALTER TABLE "UserMemory" ALTER COLUMN "content" DROP NOT NULL;

ALTER TABLE "Prediction" ALTER COLUMN "userId" DROP NOT NULL;
ALTER TABLE "Prediction" ALTER COLUMN "question" DROP NOT NULL;
ALTER TABLE "Prediction" ALTER COLUMN "prediction" DROP NOT NULL;
