-- OracleMind 最终补列SQL — 补全所有缺失列

-- AgentTrace
ALTER TABLE "AgentTrace" ADD COLUMN IF NOT EXISTS "content" TEXT;
ALTER TABLE "AgentTrace" ADD COLUMN IF NOT EXISTS "agentName" TEXT;
ALTER TABLE "AgentTrace" ADD COLUMN IF NOT EXISTS "round" INTEGER;

-- GraphNode
ALTER TABLE "GraphNode" ADD COLUMN IF NOT EXISTS "nodeType" TEXT;
ALTER TABLE "GraphNode" ADD COLUMN IF NOT EXISTS "name" TEXT;
ALTER TABLE "GraphNode" ADD COLUMN IF NOT EXISTS "attributes" TEXT;

-- GraphEdge
ALTER TABLE "GraphEdge" ADD COLUMN IF NOT EXISTS "fromNodeId" TEXT;
ALTER TABLE "GraphEdge" ADD COLUMN IF NOT EXISTS "toNodeId" TEXT;
ALTER TABLE "GraphEdge" ADD COLUMN IF NOT EXISTS "relationType" TEXT;

-- Simulation
ALTER TABLE "Simulation" ADD COLUMN IF NOT EXISTS "type" TEXT;
ALTER TABLE "Simulation" ADD COLUMN IF NOT EXISTS "seedInput" TEXT;
ALTER TABLE "Simulation" ADD COLUMN IF NOT EXISTS "graphSnapshot" TEXT;
ALTER TABLE "Simulation" ADD COLUMN IF NOT EXISTS "baziSnapshot" TEXT;
ALTER TABLE "Simulation" ADD COLUMN IF NOT EXISTS "agentCount" INTEGER DEFAULT 10;
ALTER TABLE "Simulation" ADD COLUMN IF NOT EXISTS "rounds" INTEGER;
ALTER TABLE "Simulation" ADD COLUMN IF NOT EXISTS "status" TEXT;
ALTER TABLE "Simulation" ADD COLUMN IF NOT EXISTS "completedAt" TIMESTAMP(3);

-- ScenarioOutcome
ALTER TABLE "ScenarioOutcome" ADD COLUMN IF NOT EXISTS "simulationId" TEXT;
ALTER TABLE "ScenarioOutcome" ADD COLUMN IF NOT EXISTS "label" TEXT;
ALTER TABLE "ScenarioOutcome" ADD COLUMN IF NOT EXISTS "probability" DOUBLE PRECISION;
ALTER TABLE "ScenarioOutcome" ADD COLUMN IF NOT EXISTS "reasoning" TEXT;

-- WhatIfBranch
ALTER TABLE "WhatIfBranch" ADD COLUMN IF NOT EXISTS "simulationId" TEXT;
ALTER TABLE "WhatIfBranch" ADD COLUMN IF NOT EXISTS "hypotheticalChange" TEXT;
ALTER TABLE "WhatIfBranch" ADD COLUMN IF NOT EXISTS "outcome" TEXT;

-- UserMemory
ALTER TABLE "UserMemory" ADD COLUMN IF NOT EXISTS "userId" TEXT;
ALTER TABLE "UserMemory" ADD COLUMN IF NOT EXISTS "type" TEXT;
ALTER TABLE "UserMemory" ADD COLUMN IF NOT EXISTS "content" TEXT;
ALTER TABLE "UserMemory" ADD COLUMN IF NOT EXISTS "importance" DOUBLE PRECISION DEFAULT 0;

-- VerificationFeedback
ALTER TABLE "VerificationFeedback" ADD COLUMN IF NOT EXISTS "accuracy" INTEGER;
ALTER TABLE "VerificationFeedback" ADD COLUMN IF NOT EXISTS "comment" TEXT;

-- PublicAccuracy
ALTER TABLE "PublicAccuracy" ADD COLUMN IF NOT EXISTS "totalPredictions" INTEGER DEFAULT 0;
ALTER TABLE "PublicAccuracy" ADD COLUMN IF NOT EXISTS "verifiedCount" INTEGER DEFAULT 0;
ALTER TABLE "PublicAccuracy" ADD COLUMN IF NOT EXISTS "accurateCount" INTEGER DEFAULT 0;
ALTER TABLE "PublicAccuracy" ADD COLUMN IF NOT EXISTS "accuracyRate" DOUBLE PRECISION;

-- Prediction
ALTER TABLE "Prediction" ADD COLUMN IF NOT EXISTS "userId" TEXT;
ALTER TABLE "Prediction" ADD COLUMN IF NOT EXISTS "question" TEXT;
ALTER TABLE "Prediction" ADD COLUMN IF NOT EXISTS "prediction" TEXT;
ALTER TABLE "Prediction" ADD COLUMN IF NOT EXISTS "confidence" DOUBLE PRECISION;

-- LifeEvent
ALTER TABLE "LifeEvent" ADD COLUMN IF NOT EXISTS "userId" TEXT;
ALTER TABLE "LifeEvent" ADD COLUMN IF NOT EXISTS "type" TEXT;
ALTER TABLE "LifeEvent" ADD COLUMN IF NOT EXISTS "title" TEXT;
ALTER TABLE "LifeEvent" ADD COLUMN IF NOT EXISTS "description" TEXT;
ALTER TABLE "LifeEvent" ADD COLUMN IF NOT EXISTS "happenedAt" TIMESTAMP(3);
